name: Weather API Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test Python Weather API call
      run: python3 ./weather-api.py

